Issue/12 add shop
youngeek-0410/mottake pull request #27
Opened 2021-09-14 03:26 UTC by is-hoku

# 概要

shopのコントローラとルータの追加

# 対応するIssue

#close 12

# 修正内容の確認方法

エンドポイント
- GET /shop/[uid]
- POST /management/shop
- PATCH /management/shop
- DELETE /management/shop

ボディ
```
{
    "uid": "",
    "name": "",
    "image": "",
    "address": "",
    "latitude": 0.0,
    "longitude": 0.0,
    "sales_goal": 0,
    "sales": 0,
    "description": ""
}
```

リクエストボディを上の形式で作成し、POST/PATCH/DELETEをして登録（更新）後のJSONが返ってこれば成功。  
uidとlatitude, longitudeはセットする必要なし。
# レビューのポイント

# 備考

2021-09-14 04:26 UTC, Dz0526 requested changes

2021-09-14 04:26 UTC, Dz0526 commented on server/controllers/shop.go
> +func (i ShopController) Get(c *gin.Context) {
コントローラのアクション名はもうちょい適切な名前あると思う。ふきのんのやつとか

2021-09-15 08:51 UTC, Dz0526 commented on server/controllers/shop.go
> +func (i ShopController) Get(c *gin.Context) {
変わってなくない？？
@is-hoku

2021-09-15 10:49 UTC, is-hoku commented on server/controllers/shop.go
> +func (i ShopController) Get(c *gin.Context) {
ごめん、今変えた。あと動作とかの確認をお願い

2021-09-15 11:26 UTC, Dz0526 submitted a review, later dismissed
LGTM

2021-09-15 13:26 UTC, yuta0709 approved these changes
LGTM

2021-09-15 13:27 UTC, merged